name: lista_tarefas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  color_palette_plus: ^2.0.0
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  image_picker: ^1.1.2
  firebase_core: ^3.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
