// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC241QWX-KNK9ya63sT3OyNWgotKYzetdw',
    appId: '1:67816503041:web:3af68def5f9b986a334d00',
    messagingSenderId: '67816503041',
    projectId: 'lista-tarefas-2ed64',
    authDomain: 'lista-tarefas-2ed64.firebaseapp.com',
    storageBucket: 'lista-tarefas-2ed64.firebasestorage.app',
    measurementId: 'G-25L1GPF2PH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH2q-NGCQ3S6jwrwxMariuDDEbhaVGH_E',
    appId: '1:67816503041:android:67d4111f2c677f26334d00',
    messagingSenderId: '67816503041',
    projectId: 'lista-tarefas-2ed64',
    storageBucket: 'lista-tarefas-2ed64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgLFMQNYrqO3BqtwcYW1Nnjx4QcVMNz4s',
    appId: '1:67816503041:ios:1a79c177ca336f2e334d00',
    messagingSenderId: '67816503041',
    projectId: 'lista-tarefas-2ed64',
    storageBucket: 'lista-tarefas-2ed64.firebasestorage.app',
    iosBundleId: 'com.example.listaTarefas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgLFMQNYrqO3BqtwcYW1Nnjx4QcVMNz4s',
    appId: '1:67816503041:ios:1a79c177ca336f2e334d00',
    messagingSenderId: '67816503041',
    projectId: 'lista-tarefas-2ed64',
    storageBucket: 'lista-tarefas-2ed64.firebasestorage.app',
    iosBundleId: 'com.example.listaTarefas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC241QWX-KNK9ya63sT3OyNWgotKYzetdw',
    appId: '1:67816503041:web:82b1ecbcb62cdbcb334d00',
    messagingSenderId: '67816503041',
    projectId: 'lista-tarefas-2ed64',
    authDomain: 'lista-tarefas-2ed64.firebaseapp.com',
    storageBucket: 'lista-tarefas-2ed64.firebasestorage.app',
    measurementId: 'G-8REFH3LDZE',
  );
}
